### ISSUE TITLE
styling first page

### ISSUE THREAD

**Issue by daniel-mlr** [daniel-mlr/echos-gatsby#1]
styling first page

- [x] Set the preview image to the blog card
- [x] Change grid layout to flex layout
- [x] Add a brief description in the blog card between the date and "more..." word

**Comment by undead85** [comment]
@daniel-mlr I could not find how to get a summary of the blog. One alternative is to create a new field in the model content of the blog for that objective.

**Comment by daniel-mlr** [comment]
I found it.  Working on it now.
