### ISSUE TITLE
format the landing page according to the mockup.

### ISSUE THREAD

**Issue by daniel-mlr** [daniel-mlr/echos-gatsby#19]
The contentful data have been updated to mimic the content I have used in the mockups.
Those mockups are available   [here](http://lesechosdupacifique.info/nouveau/).

The chosen model is model 1. 

The top big image (jumbotron), which determine the whole page width, should probably be limited when viewed on a large screen.  There are other images in the src/images/ directory which could serve as a jumbotron, maybe in a carousel (fade-in-out).

**Comment by daniel-mlr** [comment]
Bulma have been added to the dependencies.  If we use it, we should remove other style files to avoid confusion.

**Comment by undead85** [comment]
There are 3 components to format on the landing page.

- [ ] Jumbotron #23 
- [ ] ConcertGridCard #24
- [ ] BlogGridCard #25

**Comment by undead85** [comment]
@daniel-mlr I split this issue en 3 different. Let me know in what issue are you working on.

**Comment by daniel-mlr** [comment]
There’s also the header and footer (in the layout). I will create an issue and take it. You can take the jumbotron, as I’m struggling with it to make it cover the whole viewport width on large screens without cropping the top and bottom. Maybe we will have to set a max-width for large screen, but I think it is more impressive if the image covers the full screen width. Can you give it a try.

**Comment by daniel-mlr** [comment]
Mostly done.  Some layout problems with certain screen sizes.  Will be reopened under more relevant descriptions.
