### ISSUE TITLE
Master broken

### ISSUE THREAD

**Issue by undead85** [daniel-mlr/echos-gatsby#20]
The master branch is broken. Can you upload the favicon file, please?

https://github.com/daniel-mlr/echos-gatsby/blob/b5255be81e00ff91ed1631e81c5d0304167a1fb4/gatsby-config.js#L54

**Comment by daniel-mlr** [comment]
I removed temporarily the 'gatsby-plugin-favicon' plugin because I find it extremely slow to build.  
It seems the .ico files got removed from the repo because of .gitignore
You can get the favicon [here](https://res.cloudinary.com/danielmeilleurimg/image/upload/v1562726460/echos/favicon.png)

**Comment by undead85** [comment]
I can change the .gitignore file and upload the png file. Are you ok with this?

**Comment by daniel-mlr** [comment]
Yes, but I'm not sure if it is good practice to store binary files on github repo.

**Comment by daniel-mlr** [comment]
I use [cloudinary](https://cloudinary.com) as image repo.  Maybe it is possible to use it in the project?

**Comment by daniel-mlr** [comment]
Can you access to this url: [https://cloudinary.com/console/media_library/folders/all/echos](https://cloudinary.com/console/media_library/folders/all/echos)? This is where all images for the project are stored.

**Comment by undead85** [comment]
> Yes, but I'm not sure if it is good practice to store binary files on github repo.

I don see a problem with uploading static images.

> Can you access to this url: https://cloudinary.com/console/media_library/folders/all/echos? This is where all images for the project are stored.

No. it shows me a Login access

**Comment by daniel-mlr** [comment]
I just found out I cannot add a user on cloudinary free plan.  So ok, let's go for static images on github.
