### ISSUE TITLE
TypeError: Cannot read property 'childImageSharp' of null

### ISSUE THREAD

**Issue by undead85** [daniel-mlr/echos-gatsby#21]
Web browser shows this error:

> TypeError: Cannot read property 'childImageSharp' of null
Jumbotron
C:/Users/Angel/Documents/echos-gatsby-master/src/components/jumbotron.js:30

When execute this in GraphiQL

https://github.com/daniel-mlr/echos-gatsby/blob/41de253d3b4ccf34e03bc537b68d943f45d63eed/src/components/jumbotron.js#L14-L19

the result is:

`"file": null`

Don't find the file `nom_femme-crop-1920x1200`

**Comment by daniel-mlr** [comment]
Same as [preceding issue](https://github.com/daniel-mlr/echos-gatsby/issues/20).  Here is the [image file](https://res.cloudinary.com/danielmeilleurimg/image/upload/v1560323995/echos/nom_femme-crop-1920x1200.jpg)
