### ISSUE TITLE
Change splash picture in hero to prevent overwriting on face in small screens.

### ISSUE THREAD

**Issue by daniel-mlr** [daniel-mlr/echos-gatsby#40]
Experiment with position of text in the hero so as to avoid covering the woman's face with text when the viewport shrinks. Maybe try with one of the 'elongated' pictures (1920x1020 or 1920x800) in `/src/images/`.

**Comment by undead85** [comment]
maybe for a mobile version, you will need a new one with vertical space (elongated vertically)

**Comment by daniel-mlr** [comment]
Resolved in having media queries for positioning site name and subname
