### ISSUE TITLE
Style burger menu colors

### ISSUE THREAD

**Issue by daniel-mlr** [daniel-mlr/echos-gatsby#49]
Style burger menu colors by choosing from brand colors (see `src/styles/variables.scss`) or creating new ones, as needed, to maximise legibility.

**Comment by undead85** [comment]
Burger menu already has the brand colors
https://github.com/daniel-mlr/echos-gatsby/blob/6085e29d72ab667edf89abdc292b9838da64e0a3/src/styles/burgerMenu.scss#L13-L20

**Comment by daniel-mlr** [comment]
Oops sorry, forgot to push my updates on remote. Will do tomorrow.
