### ISSUE TITLE
Collapsible menu

### ISSUE THREAD

**Issue by daniel-mlr** [daniel-mlr/echos-gatsby#5]
Collapsible menu to 'hamburger' menu when wiew width is below a limit, for phone and tablets. Also make images responsive.
**Useful resources:**
[https://www.gatsbyjs.org/docs/centralizing-your-sites-navigation/](https://www.gatsbyjs.org/docs/centralizing-your-sites-navigation/)
[https://www.npmjs.com/package/react-burger-menu](https://www.npmjs.com/package/react-burger-menu)

**Comment by undead85** [comment]
@daniel-mlr I create a new issue with the task "make images responsive" #15
