### ISSUE TITLE
Make the menu labels bilingual

### ISSUE THREAD

**Issue by daniel-mlr** [daniel-mlr/echos-gatsby#58]
With the language feature now implemented, we should also have a bilingual menu by drawing `site.siteMetadata` into the big query of `index.js` and using it to display the menu items in the chosen language. I had started to do it before but I am not sure how. Translations are there, in the `gatsby-config.js` file.

BTW: Maybe we should display only one link for language: i.e. _english_ when the current locale is french, and _français_ when the current locale is english. It takes less room and prevent folding.

**Comment by daniel-mlr** [comment]
Also make buttons labels depend on the language.
Lire <--> Read
Lire les autres articles <--> Read More News 

And:
Make the section separators in the _concert_ page  language dependant
Nos prochains concerts <--> Our Coming Concerts
Nos précédents concerts <--> Our Past Concerts

**Comment by undead85** [comment]
@daniel-mlr I found the [issue ](https://github.com/gatsbyjs/gatsby/issues/10990) in Gatsby about the problem with filtering the sitemetadata. 
I am searching for an alternative.

**Comment by undead85** [comment]
> **Also** make buttons labels depend on the language.
> Lire <--> Read
> Lire les autres articles <--> Read More News
> 
> **And**:
> Make the section separators in the _concert_ page language dependant
> Nos prochains concerts <--> Our Coming Concerts
> Nos précédents concerts <--> Our Past Concerts

I created issue #65 for it
